# Generated by Django 5.2.1 on 2025-11-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='prioridad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_espera',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_estimado_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_preparacion',
            field=models.FloatField(default=5.0),
        ),
    ]
