# Generated by Django 5.2.8 on 2025-11-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_pedido_prioridad_pedido_tiempo_espera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='en_preparacion',
            field=models.BooleanField(default=False),
        ),
    ]
